import {strict as assert} from "node:assert";
import {buildArrangement,parseKey,parseChord} from "../src/arranger.js";
assert.deepEqual(parseKey("G major"),{root:7,mode:"major"});
assert.deepEqual(parseChord("Em"),{root:4,mode:"minor"});
const timeline=[{startSec:0,endSec:4,chord:"G"},{startSec:4,endSec:8,chord:"C"}];
const muteRegions=[{startSec:2,endSec:3,kind:"mute",label:"speech"}];
const a=buildArrangement({bpm:120,durationSec:8,key:"G major",seed:7,chordTimeline:timeline,muteRegions});
assert.equal(a.bars,4);assert.equal(a.chordAware,true);
assert.ok(a.drums.length>0&&a.bass.length>0&&a.lead.length>0);
assert.ok(a.drums.every(e=>e.time<8));
assert.ok(a.drums.every(e=>!(e.time>=2&&e.time<3)));
assert.ok(a.bass.every(e=>!(e.time>=2&&e.time<3)));
assert.equal(a.bass[0].midi,43);
assert.ok(a.bass.some(e=>e.chord==="C"));
assert.deepEqual(a,buildArrangement({bpm:120,durationSec:8,key:"G major",seed:7,chordTimeline:timeline,muteRegions}));
console.log("arranger tests passed");
